[package]
name = "unpacker"
version = "0.1.0"
authors = ["travistrue2008 <travis.true08@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.4"
clap = "2.33.0"
image = "0.23.2"
rust-crypto = "0.2.36"
tim2 = { path = "../tim2/lib" }
