[package]
name = "unpacker"
version = "0.1.0"
authors = ["travistrue2008 <travis.true08@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.4"
rust-crypto = "0.2.36"
image = "0.23.2"
iso9660 = "0.1.1"
tim2 = "0.3.1"
walkdir = "2.3.3"
